# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f28cfd02d3e5f67843821a91967b0b2c822fe63eb3b3f5229a6971429f8a7c3b93e2ed6fde40ce8ccbf8c3d97ac6c565e5557196a01d2827ef08eb915765f8d

test:
  secret_key_base: 3191f82d4f461f116b19c2417baf47be1511d1a67cc5e3e41f6b30a2c32c10c5e755ac2571c44a2adee4ebd7209e7bd9cad07dca7df6c7e27f44097a77217d26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
